### PR TITLE
Add Docs For Create Inline on Relationships

### PR DESCRIPTION
**Pull request by andrewlinfoot**

### CODE REVIEW

**Comment by ericelliott** [comment]
Does this need any further explanation?

**Comment by morenoh149** [comment]
corresponds to https://github.com/keystonejs/keystone/pull/2132 It's good practice to mention the related issue/pr

**Comment by andrewlinfoot** [comment]
@ericelliott Probably, I wasn't exactly sure where to put more info because I just saw the new docs site today. I figured that one spot seemed obvious so I added it and would take another look at possibly adding more documentation later.

@morenoh149 thanks :) will do next time. Is it a best practice to open an issue for every PR for discussion and tracking, even when the PR is a rather simple fix or addition?

**Comment by andrewlinfoot** [comment]
Here is the original PR for createInline: https://github.com/keystonejs/keystone/pull/2093

**Comment by morenoh149** [comment]
PRs themselves can have comments so I think it may be redundant to open an issue for every PR.

**Comment by andrewlinfoot** [comment]
@morenoh149 Got it, thanks :)

**Comment by JedWatson** [comment]
:+1: thanks @andrewlinfoot!

**Pull request merged**
